### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by tomasesquivelgc** [ivangonzalez224/Recipe-app#21]
# Ruby on Rails group project
- [Link to the kanban board](https://github.com/users/ivangonzalez224/projects/8)
- In this project there are only 2 members.

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi Team,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] You provided a broken link to your project Kanban cards. Please fix that.

![image](https://github.com/ivangonzalez224/Recipe-app/assets/68796232/98b90b38-fe85-4153-9de3-a35d457aafe7)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by tomasesquivelgc** [comment]
Thank you for your review, the issue has been fixed and the link should be working now.

**Comment by 1GORDON** [comment]
##
## Hi @tomasesquivelgc, and @ivangonzalez224 ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- As stated in the project requirements, each requirement is supposed to be represented on your Kanban board. Kindly add a card for this requirement.
![N+1 Queries](https://github.com/ivangonzalez224/Recipe-app/assets/63917725/039b4cce-3694-4d38-bbf7-210b7646b2d2)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tomasesquivelgc** [comment]
# Changes
The n+1 problem issue has been added to the project

**Comment by FrederickMih** [comment]
## Hi :raising_hand: :raising_hand: @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Project requirement *"Make sure there're no N+1 queries happening"* has been included in a card :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
